### PR TITLE
fix #5

### LINKED ISSUE #5: raise RuntimeError(f'Maximum of {max} pages exceeded')
Got this by adding "infusionsoft.contrib.django"

```python+traceback
Traceback (most recent call last):
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/vagrant/.virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/infusionsoft/__init__.py", line 9, in <module>
    import infusionsoft.query
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/infusionsoft/query.py", line 32
    raise RuntimeError(f'Maximum of {max} pages exceeded')
```

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by theY4Kman** [comment]
Hey, thanks for making the pull request :) I'd never heard of the [ww](https://github.com/tygs/ww/) library before, it's pretty neat. I love those hacky little backports, reading vars from other stack frames — pytest's assertions also come to mind.

Anyway, instead of adding an external dependency, I'd rather just change the f strings to use vanilla `.format()`. I'll make that change and release a new version today.

**Comment by bashu** [comment]
great!

**Comment by theY4Kman** [comment]
Oh, yeah, I forgot to mention I released 1.3.1, in case you missed it.

**Comment by bashu** [comment]
@theY4Kman already using it, thanks!

**Pull request closed without merging**
